---
# hosts_root: "/home/t9md/dev/pxelerator/hostiis"
api_base: "http://localhost:9393"
mirror_url: "http://localhost/mirror"
pxelinux_cfg_dir: "/tftpboot/pxelinux.cfg"
mirror_dir: "/var/www/html/mirror"
# dnsmasq_conf: "/etc/dnsmasq.d/pxelerator.conf"
dnsmasq_conf: "/home/t9md/local/pxelerator/dnsmasq_pxelerator.conf"
# dnsmasq_conf: "/etc/dnsmasq.d/pxelerator.conf"
